### ISSUE TITLE
(feature) Support the new regex API names str.to_re and str.in_re

### ISSUE THREAD

**Issue by rainoftime** [uuverifiers/ostrich#24]
Hi,
According to http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml

The two regex operations `str.to.re` and `str.in.re` have been changed to `str.to_re` and `str.in_re`.
Is there any plan for supporting the new API names?

**Comment by albins** [comment]
Hi! Thanks for reporting this. We're working on a fix and it's planned. :)

**Comment by pruemmer** [comment]
The new function names should be accepted in the latest master!
