### ISSUE TITLE
Refutational soundness issue on QF_UFNRA formula

### ISSUE THREAD

**Issue by rainoftime** [uuverifiers/ostrich#5]
Hi, for the following instances
[nra1.txt](https://github.com/uuverifiers/ostrich/files/4923865/nra1.txt)
[nra2.txt](https://github.com/uuverifiers/ostrich/files/4923867/nra2.txt)

ostrich 2b3eb9b returns `unsat`, but both z3 and yices2 (latest commits) return `sat` .

**Comment by rainoftime** [comment]
A model returned by Yices2 for the first instance
~~~~
sat
(= v0 false)
(= v1 false)
(= v2 false)
(= v6 true)
(= v8 false)
(= v9 false)
(= v13 false)
(= v16 false)
(= v17 true)
(= v18 false)
(= r1 (- 470043))
(= r7 1)
(= r16 0)
(= r17 1)
~~~~

**Comment by uuverifiers** [comment]
For which version of OSTRICH does this happen? The release version 1.0.1
does not actually support reals, but might not complain about them;
reals will internally be treated as integers, and this can of course
lead to wrong results.

OSTRICH is an SMT solvers strictly for the QF_SLIA logic
(quantifier-free string constraints with integers).

**Comment by rainoftime** [comment]
I clone the lastest commit and build the jar file with the command `sbt assembly`.
