### ISSUE TITLE
Underscore in regex pattern causes parse error

### ISSUE THREAD

**Issue by amandasystems** [uuverifiers/ostrich#50]
Minimal failing example ([online version](http://logicrunch.it.uu.se:4096/~wv/princess/?ex=perma%2F1648716057_1664046336
)):

```smtlib
(declare-const w String)
(assert (str.in.re w (re.from_ecma2020 '_')))
(check-sat)
```

**Comment by pruemmer** [comment]
The last commit should fix this problem!
