### ISSUE TITLE
Compilation Error: Failed 4 out of 354 tests in Ostrich

### ISSUE THREAD

**Issue by Ding0042** [uuverifiers/ostrich#76]
Hello, I am facing an issue while trying to compile Ostrich. The compilation fails with the following error message:
`[info] Failed: Total 354, Failed 4, Errors 0, Passed 350`.
Additionally, the number of failures varies with each run.

I believe I have successfully installed sbt, as the command `sbt sbtVersion` outputs 
`[info] welcome to sbt 1.9.7 (Private Build Java 17.0.8.1)`.

Environment:
Operating System: Ubuntu 20.04.6 LTS

Is there any solution to this issue?
Thanks for your help!

**Comment by uuverifiers** [comment]
I just tried compilation using different Java versions (11 and 18), and 
it always worked. Could it be that your machine is rather slow, so that 
some of the test cases are running into timeouts?

You can start a build without any tests using the command

sbt "set assembly / test := {}" clean assembly

Maybe that works for you?

**Comment by mimo0428** [comment]
Thank you very much for your help!!
After multiple attempts, I was able to compile successfully. Perhaps your guess was correct. 
Furthermore, I have another inquiry.
I'm interested in testing the execution time, and I think directly measuring the command line execution time may not be very accurate. But I don't seem to see any command-line parameters for measuring execution time? Could you please enlighten me on how you typically measure execution time during experiments?

**Comment by uuverifiers** [comment]
Ok, great!

If you add the option "+logo", the runtime (wall-clock time) for each 
solved problem will be displayed. But the "time" command should be 
accurate as well!

**Comment by mimo0428** [comment]
Thank you for your help!! 
I can proceed with the statistics with `./ostrich` now. 
Actually, I had noticed the `+logo` parameter before, but I ran `./ostrich-client +logo` and didn't get the statistical results.
The reason I chose to run `./ostrich-client` is that I found its runtime to be a bit shorter.
