### ISSUE TITLE
API

### ISSUE THREAD

**Issue by AnkitMU** [uuverifiers/ostrich#83]
Does Ostrich supports JAVA API or any API's???

**Comment by pruemmer** [comment]
Sure; Ostrich is included in the Java-SMT library, which you can use to interface the solver from Java: https://github.com/sosy-lab/java-smt

There is also a Scala API, here is an example: https://github.com/uuverifiers/ostrich/blob/e386836dba365bd9045cba440cda8ec9b115b19d/src/test/scala/APITest.scala
